name: multistages
on:
  workflow_dispatch:

jobs:
  clone:
    name: clone
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
      with:
        repository: DaggupatiPavan/java-web-app-docker

    - name: Upload workspace to artifact
      uses: actions/upload-artifact@v3
      with:
        name: workspace
        path: .

  Build:
    runs-on: ubuntu-latest
    needs: clone
    steps:
    - name: Download workspace from artifact
      uses: actions/download-artifact@v3
      with:
        name: workspace
        path: .

    - name: Maven build (stdout, stderr capture)
      shell: bash
      run: |
        echo "Starting Maven build at $(date)" >> build_execution_times.txt
        mvn clean package > ${{ github.workspace }}/build_stdout.log 2> ${{ github.workspace }}/build_stderr.log
        echo "Maven build completed at $(date)" >> build_execution_times.txt

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: target/*.jar  # Only upload the built artifacts

    - name: Upload Maven logs
      uses: actions/upload-artifact@v3
      with:
        name: maven-logs
        path: |
          ${{ github.workspace }}/build_stdout.log
          ${{ github.workspace }}/build_stderr.log

  ImageBuild:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: .

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build (stdout, stderr capture)
      shell: bash
      run: |
        echo "Building Docker image at $(date)" >> build_execution_times.txt
        docker build -t pavan176/webapp:v.0.1 . > ${{ github.workspace }}/docker_build_stdout.log 2> ${{ github.workspace }}/docker_build_stderr.log
        echo "Docker image build completed at $(date)" >> build_execution_times.txt

    - name: Upload Docker build logs
      uses: actions/upload-artifact@v3
      with:
        name: docker-build-logs
        path: |
          ${{ github.workspace }}/docker_build_stdout.log
          ${{ github.workspace }}/docker_build_stderr.log

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: pavan176/webapp:v.0.1
        platforms: linux/amd64,linux/arm64

  RunImage:
    runs-on: self-hosted
    needs: ImageBuild
    steps:
    - name: Run Docker container (stdout, stderr capture)
      shell: bash
      run: |
        echo "Running Docker container at $(date)" >> build_execution_times.txt
        docker run -itd pavan176/webapp:v.0.1 > ${{ github.workspace }}/docker_run_stdout.log 2> ${{ github.workspace }}/docker_run_stderr.log
        echo "Docker container started at $(date)" >> build_execution_times.txt

    - name: Upload Docker run logs
      uses: actions/upload-artifact@v3
      with:
        name: docker-run-logs
        path: |
          ${{ github.workspace }}/docker_run_stdout.log
          ${{ github.workspace }}/docker_run_stderr.log
