name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Automatically triggers on push to 'main' branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build the project using Maven
      - name: Build
        run: |
          mvn clean install
          echo "Maven build completed"

      # Step 3: Run unit tests with Maven
      - name: Test
        run: mvn test

      # Step 4: Generate Dockerfile
      - name: Write Dockerfile
        run: |
          echo "FROM openjdk:8-jre" >> Dockerfile
          echo "EXPOSE 8080" >> Dockerfile
          echo "COPY target/*.jar /usr/src/myapp.jar" >> Dockerfile
