name: Testing-pipelinecode
'on':
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: TCS/Nextgen
        token: "${ secrets.'nextgen-devops-token'\n }"
        ref: DevOps
    - name: Build
      run:
      - mvn clean install
      - echo maven completed
    - name: Set up SonarQube environment
      uses: sonarsource/sonarqube-scan-action@v1.0
      with:
        sonarQubeEnv:
          credentialsId: sonarQube
          installationName: QualityChecks
    - name: SonarQube
      run:
      - mvn clean verify sonar:sonar -Dsonar.projectKey=genai -Dsonar.projectName='genai'
    - name: Test
      run:
      - mvn test
    - name: Write Dockerfile
      run:
      - echo "FROM openjdk:8-jre" >> Dockerfile
      - echo "EXPOSE 8080" >> Dockerfile
      - echo "COPY target/*.jar /usr/src/myapp.jar" >> Dockerfile
    - name: Docker Build
      run:
      - docker build -t abhishekraov/palto_alto:${params.dockertag} .
    - name: Push to DockerHub
      run:
      - docker push abhishekraov/palto_alto:${params.dockertag}
    - name: Deploy as Pod
      run:
      - kubectl delete pod paltoalto || true
      - kubectl run paltoalto --image=abhishekraov/palto_alto:${params.dockertag}
